export const BOARD_TEMPLATES = [
  {
    id: 'sprint',
    name: 'Software Sprint',
    description: 'Agile sprint board with backlog, in progress, review, and done groups',
    color: '#0073ea',
    icon: '🚀',
    groups: [
      { id: 'backlog', title: 'Backlog', color: '#c4c4c4', position: 0 },
      { id: 'sprint', title: 'Sprint', color: '#579bfc', position: 1 },
      { id: 'in_progress', title: 'In Progress', color: '#fdab3d', position: 2 },
      { id: 'review', title: 'Code Review', color: '#a25ddc', position: 3 },
      { id: 'done', title: 'Done', color: '#00c875', position: 4 },
    ],
    columns: [
      { id: 'status', title: 'Status', type: 'status', width: 140 },
      { id: 'person', title: 'Developer', type: 'person', width: 130 },
      { id: 'date', title: 'Due Date', type: 'date', width: 120 },
      { id: 'priority', title: 'Priority', type: 'priority', width: 130 },
    ],
    sampleTasks: ['Set up project repo', 'Design database schema', 'Build API endpoints', 'Create UI components', 'Write unit tests'],
  },
  {
    id: 'marketing',
    name: 'Marketing Campaign',
    description: 'Track campaigns from ideation to launch and analysis',
    color: '#ff642e',
    icon: '📢',
    groups: [
      { id: 'ideation', title: 'Ideation', color: '#579bfc', position: 0 },
      { id: 'planning', title: 'Planning', color: '#fdab3d', position: 1 },
      { id: 'in_progress', title: 'In Progress', color: '#00c875', position: 2 },
      { id: 'launched', title: 'Launched', color: '#a25ddc', position: 3 },
    ],
    columns: [
      { id: 'status', title: 'Status', type: 'status', width: 140 },
      { id: 'person', title: 'Owner', type: 'person', width: 130 },
      { id: 'date', title: 'Launch Date', type: 'date', width: 120 },
      { id: 'priority', title: 'Priority', type: 'priority', width: 130 },
    ],
    sampleTasks: ['Define target audience', 'Create content calendar', 'Design social media assets', 'Set up ad campaigns'],
  },
  {
    id: 'onboarding',
    name: 'HR Onboarding',
    description: 'New employee onboarding checklist and process tracking',
    color: '#00c875',
    icon: '👋',
    groups: [
      { id: 'pre_arrival', title: 'Pre-Arrival', color: '#579bfc', position: 0 },
      { id: 'first_day', title: 'First Day', color: '#fdab3d', position: 1 },
      { id: 'first_week', title: 'First Week', color: '#00c875', position: 2 },
      { id: 'first_month', title: 'First Month', color: '#a25ddc', position: 3 },
    ],
    columns: [
      { id: 'status', title: 'Status', type: 'status', width: 140 },
      { id: 'person', title: 'Responsible', type: 'person', width: 130 },
      { id: 'date', title: 'Due Date', type: 'date', width: 120 },
      { id: 'priority', title: 'Priority', type: 'priority', width: 130 },
    ],
    sampleTasks: ['Send welcome email', 'Set up workstation', 'HR orientation', 'Team introductions', 'First project assignment'],
  },
  {
    id: 'crm',
    name: 'CRM Pipeline',
    description: 'Sales pipeline with leads, qualified, proposal, and closed stages',
    color: '#a25ddc',
    icon: '💼',
    groups: [
      { id: 'leads', title: 'New Leads', color: '#579bfc', position: 0 },
      { id: 'qualified', title: 'Qualified', color: '#fdab3d', position: 1 },
      { id: 'proposal', title: 'Proposal Sent', color: '#ff642e', position: 2 },
      { id: 'closed', title: 'Closed Won', color: '#00c875', position: 3 },
    ],
    columns: [
      { id: 'status', title: 'Stage', type: 'status', width: 140 },
      { id: 'person', title: 'Sales Rep', type: 'person', width: 130 },
      { id: 'date', title: 'Close Date', type: 'date', width: 120 },
      { id: 'priority', title: 'Deal Size', type: 'priority', width: 130 },
    ],
    sampleTasks: ['Acme Corp initial contact', 'Beta Inc demo scheduled', 'Gamma LLC proposal review'],
  },
  {
    id: 'tracker',
    name: 'Project Tracker',
    description: 'General project management with milestones and deliverables',
    color: '#579bfc',
    icon: '📊',
    groups: [
      { id: 'planning', title: 'Planning', color: '#579bfc', position: 0 },
      { id: 'in_progress', title: 'In Progress', color: '#fdab3d', position: 1 },
      { id: 'completed', title: 'Completed', color: '#00c875', position: 2 },
    ],
    columns: [
      { id: 'status', title: 'Status', type: 'status', width: 140 },
      { id: 'person', title: 'Owner', type: 'person', width: 130 },
      { id: 'date', title: 'Deadline', type: 'date', width: 120 },
      { id: 'priority', title: 'Priority', type: 'priority', width: 130 },
    ],
    sampleTasks: ['Define project scope', 'Create project plan', 'Kickoff meeting', 'First milestone review'],
  },
];
