const webpush = require('web-push');
const { Op } = require('sequelize');

// ── VAPID configuration ──────────────────────────────────────
// VAPID keys are REQUIRED for Web Push. Missing keys silently disabled the
// entire push pipeline pre-Batch-7 (a major source of "in-app toast works
// but OS notification doesn't" bug reports). We now:
//
//  1. Detect missing/blank keys and SHOUT in the startup logs so the
//     misconfig can't be silently dropped.
//  2. In NODE_ENV !== 'production', auto-generate a key pair on startup so
//     dev environments work out-of-the-box. The generated keys are logged
//     so the developer can paste them into .env for stability across
//     restarts (otherwise PushManager subscriptions become invalid every
//     restart and have to be re-created).
//  3. In production, refuse to silently fall back. We still don't crash —
//     the rest of the app must work — but `pushConfigured = false` and a
//     loud error is logged on every send attempt.
let VAPID_PUBLIC = process.env.VAPID_PUBLIC_KEY || '';
let VAPID_PRIVATE = process.env.VAPID_PRIVATE_KEY || '';
const VAPID_SUBJECT = process.env.VAPID_SUBJECT || 'mailto:admin@aniston.com';

let pushConfigured = false;
let vapidAutoGenerated = false;

function shouldAutoGenerate() {
  // Don't auto-generate in production — keys must be stable across restarts.
  return process.env.NODE_ENV !== 'production'
      && !process.env.DISABLE_VAPID_AUTOGEN;
}

if ((!VAPID_PUBLIC || !VAPID_PRIVATE) && shouldAutoGenerate()) {
  try {
    const generated = webpush.generateVAPIDKeys();
    VAPID_PUBLIC = generated.publicKey;
    VAPID_PRIVATE = generated.privateKey;
    vapidAutoGenerated = true;
    console.warn('=================================================================');
    console.warn('[Push] VAPID keys NOT set in .env — generated dev keys for this');
    console.warn('[Push] process. They will RESET on every restart, invalidating');
    console.warn('[Push] every existing browser subscription. Paste these into');
    console.warn('[Push] server/.env to make push delivery stable:');
    console.warn('[Push]');
    console.warn(`[Push]   VAPID_PUBLIC_KEY=${VAPID_PUBLIC}`);
    console.warn(`[Push]   VAPID_PRIVATE_KEY=${VAPID_PRIVATE}`);
    console.warn(`[Push]   VAPID_SUBJECT=${VAPID_SUBJECT}`);
    console.warn('[Push]');
    console.warn('[Push] After updating .env, restart the server and have each');
    console.warn('[Push] user re-allow notifications so the new subscription is');
    console.warn('[Push] saved with the matching public key.');
    console.warn('=================================================================');
  } catch (err) {
    console.error('[Push] VAPID auto-generate failed:', err.message);
  }
}

if (VAPID_PUBLIC && VAPID_PRIVATE) {
  try {
    webpush.setVapidDetails(VAPID_SUBJECT, VAPID_PUBLIC, VAPID_PRIVATE);
    pushConfigured = true;
    if (!vapidAutoGenerated) {
      console.log('[Push] VAPID configured successfully (subject: %s, public key suffix: …%s)',
        VAPID_SUBJECT,
        VAPID_PUBLIC.slice(-12));
    }
  } catch (err) {
    console.warn('[Push] VAPID configuration failed:', err.message);
  }
} else {
  // Last resort — production with no keys, or auto-gen disabled. Log loudly.
  console.error('===================================================================');
  console.error('[Push] VAPID NOT CONFIGURED — Web Push delivery is DISABLED.');
  console.error('[Push] Set VAPID_PUBLIC_KEY, VAPID_PRIVATE_KEY, VAPID_SUBJECT in .env.');
  console.error('[Push] Generate a fresh pair with:');
  console.error('[Push]   node -e "console.log(require(\'web-push\').generateVAPIDKeys())"');
  console.error('[Push] In-app toasts will continue to work; OS notifications will not.');
  console.error('===================================================================');
}

/**
 * Lazy-load the model so this file can be required before sequelize init.
 */
function getModel() {
  return require('../models').PushSubscription;
}

/**
 * Save (or re-activate) a push subscription for the authenticated user.
 *
 * Endpoint is unique-per-browser. Two important rules enforced here:
 *   1. If the SAME endpoint already exists under another userId (browser was
 *      previously signed into a different account), we re-link it to the new
 *      userId. The old user can never receive a push at this endpoint again.
 *   2. isActive is always set to true on subscribe so a re-login after logout
 *      re-enables delivery without losing the subscription history.
 *
 * Returns the persisted row (or null on failure — never throws).
 */
async function saveSubscription(userId, subscription, meta = {}) {
  if (!userId || !subscription || !subscription.endpoint) return null;
  const PushSubscription = getModel();
  if (!PushSubscription) return null;

  const endpoint = subscription.endpoint;
  const p256dh = subscription.keys?.p256dh || '';
  const auth = subscription.keys?.auth || '';

  if (!p256dh || !auth) return null;

  try {
    // Endpoint is the natural unique key. Use upsert via findOne+update/create
    // so we control re-linking when the same browser switches users.
    const existing = await PushSubscription.findOne({ where: { endpoint } });
    if (existing) {
      await existing.update({
        userId,
        p256dh,
        auth,
        userAgent: meta.userAgent || existing.userAgent,
        deviceId: meta.deviceId || existing.deviceId,
        isActive: true,
        lastSeenAt: new Date(),
        deactivatedAt: null,
      });
      return existing;
    }
    return await PushSubscription.create({
      userId,
      endpoint,
      p256dh,
      auth,
      userAgent: meta.userAgent || null,
      deviceId: meta.deviceId || null,
      isActive: true,
      lastSeenAt: new Date(),
    });
  } catch (err) {
    console.warn('[Push] saveSubscription failed:', err.message);
    return null;
  }
}

/**
 * Mark a subscription inactive (logout from this device).
 *
 * Scoped by userId AND endpoint so a user cannot deactivate someone else's
 * subscription by sending a forged endpoint. We do NOT hard-delete on logout —
 * the row is preserved (isActive=false, deactivatedAt set) so the same browser
 * re-activating on next login is a single UPDATE rather than a fresh row.
 */
async function deactivateSubscription(userId, endpoint) {
  if (!userId || !endpoint) return 0;
  const PushSubscription = getModel();
  if (!PushSubscription) return 0;
  try {
    const [count] = await PushSubscription.update(
      { isActive: false, deactivatedAt: new Date() },
      { where: { userId, endpoint } }
    );
    return count;
  } catch (err) {
    console.warn('[Push] deactivateSubscription failed:', err.message);
    return 0;
  }
}

/**
 * Mark every active subscription for this user inactive. Used by the "logout
 * all devices" path (currently unused — single-device logout is the default).
 */
async function deactivateAllForUser(userId) {
  if (!userId) return 0;
  const PushSubscription = getModel();
  if (!PushSubscription) return 0;
  try {
    const [count] = await PushSubscription.update(
      { isActive: false, deactivatedAt: new Date() },
      { where: { userId, isActive: true } }
    );
    return count;
  } catch (err) {
    console.warn('[Push] deactivateAllForUser failed:', err.message);
    return 0;
  }
}

/**
 * Hard-delete a subscription by endpoint. Called when web-push reports the
 * endpoint is permanently gone (404/410) so the row stops being retried.
 */
async function deleteByEndpoint(endpoint) {
  if (!endpoint) return 0;
  const PushSubscription = getModel();
  if (!PushSubscription) return 0;
  try {
    return await PushSubscription.destroy({ where: { endpoint } });
  } catch (err) {
    console.warn('[Push] deleteByEndpoint failed:', err.message);
    return 0;
  }
}

/**
 * Send a web push notification to every ACTIVE subscription for a user.
 *
 * Fire-and-forget from the caller's perspective: errors are logged, expired
 * endpoints are evicted from the DB, and the function never throws.
 *
 * Does nothing if VAPID is not configured (prevents `webpush.sendNotification`
 * from throwing on misconfigured environments).
 */
async function sendPushToUser(userId, payload) {
  if (!userId) {
    console.warn('[Push] sendPushToUser called without userId');
    return { sent: 0, reason: 'no-user' };
  }
  if (!pushConfigured) {
    // Loud per-call log — silent before, which masked the entire push
    // pipeline being disabled in dev environments without VAPID keys. This
    // log is the single signal a developer needs to diagnose "in-app toast
    // works but OS notification doesn't" reports.
    console.warn(
      `[Push] SKIPPED: VAPID not configured. user=${userId} title="${payload?.title || ''}". `
      + 'Set VAPID_PUBLIC_KEY/VAPID_PRIVATE_KEY/VAPID_SUBJECT in server/.env.'
    );
    return { sent: 0, reason: 'vapid-not-configured' };
  }
  const PushSubscription = getModel();
  if (!PushSubscription) return { sent: 0, reason: 'model-missing' };

  let subs = [];
  try {
    subs = await PushSubscription.findAll({
      where: { userId, isActive: true },
      attributes: ['id', 'endpoint', 'p256dh', 'auth'],
      raw: true,
    });
  } catch (err) {
    console.warn('[Push] subscription lookup failed:', err.message);
    return { sent: 0, reason: 'lookup-failed' };
  }
  if (!subs.length) {
    // Common case after a fresh deploy or after a user denies permission.
    // Log at info-level so the developer can see "no subscription for user X"
    // when diagnosing missing OS notifications. Quiet enough to not spam logs.
    console.log(`[Push] No active subscription for user=${userId} — OS notification skipped.`);
    return { sent: 0, reason: 'no-subscription' };
  }

  // Forward entity metadata so the service worker can build a stable tag
  // (collapsing duplicate pushes for the same notification) and a correct
  // deep-link target (`/boards/<id>?taskId=<id>` etc.). Defaults match the
  // pre-change behaviour for callers that don't pass extra fields.
  const data = JSON.stringify({
    title: payload.title || 'Monday Aniston',
    body: payload.body || payload.message || 'New notification',
    tag: payload.tag || (payload.notificationId ? `notif-${payload.notificationId}` : `notif-${Date.now()}`),
    url: payload.url || '/',
    notificationId: payload.notificationId || null,
    entityType: payload.entityType || null,
    entityId: payload.entityId || null,
    boardId: payload.boardId || null,
  });

  let sent = 0;
  let failed = 0;
  const sendOne = async (sub) => {
    const subscription = {
      endpoint: sub.endpoint,
      keys: { p256dh: sub.p256dh, auth: sub.auth },
    };
    try {
      await webpush.sendNotification(subscription, data);
      sent += 1;
    } catch (err) {
      failed += 1;
      const code = err?.statusCode;
      if (code === 404 || code === 410) {
        // Endpoint permanently gone — drop it.
        await deleteByEndpoint(sub.endpoint);
        console.log(`[Push] Dropped expired subscription endpoint=…${sub.endpoint.slice(-24)} (HTTP ${code})`);
      } else if (code === 401 || code === 403) {
        // Auth/VAPID error — do NOT delete (might be transient config issue).
        // Most common cause: subscription was created against a DIFFERENT
        // VAPID public key (e.g. dev re-generated keys after restart). The
        // user must re-allow permission so a fresh subscription is created
        // against the new key. Log enough detail to diagnose.
        console.warn(
          `[Push] auth error (HTTP ${code}) sending to endpoint=…${sub.endpoint.slice(-24)} `
          + 'subscription was likely created against a different VAPID key. '
          + 'Have the user re-allow notifications.'
        );
      } else {
        console.warn(`[Push] send error: ${err.message} (status=${code || 'n/a'})`);
      }
    }
  };

  await Promise.allSettled(subs.map(sendOne));
  if (sent > 0 || failed > 0) {
    console.log(`[Push] user=${userId} title="${payload?.title || ''}" sent=${sent} failed=${failed} (${subs.length} subscription(s))`);
  }
  return { sent, failed, total: subs.length };
}

module.exports = {
  pushConfigured,
  vapidPublicKey: VAPID_PUBLIC,
  saveSubscription,
  deactivateSubscription,
  deactivateAllForUser,
  deleteByEndpoint,
  sendPushToUser,
};
