-- Migration: Convert tasks.status from ENUM to VARCHAR(50) to support per-board custom statuses
-- This allows boards to define their own status labels instead of using only the global ENUM values.

-- Step 1: Add a temporary varchar column
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS status_new VARCHAR(50);

-- Step 2: Copy existing status values
UPDATE tasks SET status_new = status::text WHERE status_new IS NULL;

-- Step 3: Drop the old ENUM column
ALTER TABLE tasks DROP COLUMN IF EXISTS status;

-- Step 4: Rename the new column
ALTER TABLE tasks RENAME COLUMN status_new TO status;

-- Step 5: Set NOT NULL and default
ALTER TABLE tasks ALTER COLUMN status SET NOT NULL;
ALTER TABLE tasks ALTER COLUMN status SET DEFAULT 'not_started';

-- Step 6: Re-create the index on status
CREATE INDEX IF NOT EXISTS tasks_status ON tasks (status);

-- Step 7: Drop the old ENUM type if it exists (cleanup)
-- Note: The type name is auto-generated by Sequelize as "enum_tasks_status"
DROP TYPE IF EXISTS "enum_tasks_status";
